Runout distance
DangerKlippers/danger-klipper pull request #158
Opened 2024-02-19 12:56 UTC by Zeanon

Added a runout_distance parameter to filament switch sensors which means that after a filament_switch sensor triggers the printer will print for another `x` mm of filament (if your sensor sits at the end of a reverse bowden tube)

Filament sensor parameters can now be set via command (If you run a reverse bowden between motion sensor and extruder and retract after a print, there will be a buffer in the bowden which means you intially need a higher detection length than you would need while printint, now you can adjust it on the fly)

Added smart parameter to the sensors:
normally the sensor class uses the idle_timeout sttatus to determine whether the printer is printing, which also tiggers of you just move the toolhead (leading to false positives)
if smart is set to 1, it will use the virtual_sd_card module to determine the state, leading to no false positives but making the sensor not trigger when printing via usb stream

2024-03-22 21:05 UTC, bwnance requested changes
looks really good, thank you! just a couple things. 

Could you also clean the PR up? Sorry it's taken us this long to get to it! (Ideally the PR should just have the relevant changes in it, not a bunch of other commits, as it does now)

2024-03-22 21:05 UTC, bwnance commented on klippy/extras/filament_switch_sensor.py
> +        if not self.sensor_enabled:
**question:** shouldn't we move this `if not self.sensor_enabled` block to above the `if is_filament_present` if/else? otherwise we're dispatching events even if the sensor is disabled

2024-03-22 21:19 UTC, Zeanon commented on klippy/extras/filament_switch_sensor.py
> +        if not self.sensor_enabled:
I intentionally dispatched the events even though the sensor is disabled for mmus
But if course we can change it if you prefer

2024-03-22 21:19 UTC, Zeanon commented on klippy/extras/filament_switch_sensor.py
> +        # elif self.runout_gcode is not None:
Oh yeah, MB totally forgot to remove that

2024-03-22 21:20 UTC, Zeanon commented on klippy/extras/filament_motion_sensor.py
> +        detection_length = gcmd.get_float("DETECTION_LENGTH", None, minval=0.0)
I can look into merging it later

2024-03-23 19:16 UTC, Zeanon commented
I cleaned up the commit history and I hope I resolved all your comments
I have tested the new merged SET_FILAMENT_SENSOR command on my machine but obviously I havent had time to test it as thouroughly as before, so some feedback would be appreciated :)

2024-03-29 20:44 UTC, bwnance commented on klippy/extras/filament_switch_sensor.py
> +        # elif self.runout_gcode is not None:
@Zeanon bumping this :)

2024-03-30 12:31 UTC, rogerlz reviewed
looking good. please do a new real-world testing and it is ready to be merged

2024-03-30 13:38 UTC, rogerlz submitted a review, later dismissed

2024-03-31 12:33 UTC, Zeanon commented
For now all commands worked without issues, I guess I'll test it for some days and then report back so we can be sure that everything is definitely working

2024-04-01 01:04 UTC, rogerlz approved these changes

2024-04-01 23:58 UTC, merged