sensorless fixes
DangerKlippers/danger-klipper pull request #236
Opened 2024-05-10 20:48 UTC by rogerlz

_Enter a good description of whats being changed and WHY

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-05-15 17:16 UTC, bwnance requested changes

2024-05-15 17:16 UTC, bwnance commented on klippy/extras/tmc.py
> +        self.actual_current = self.req_run_current
**nitpick:** let's add some inline comments around what these are all for and what stuff stands for (req = requested, actual = actual current running on driver, etc)

2024-05-15 17:16 UTC, bwnance commented on klippy/extras/tmc5160.py
> +        self.actual_current = self.req_run_current
i think this is superfluous now? looks like the same line gets run in the base

2024-05-15 17:16 UTC, bwnance commented on klippy/extras/tmc.py
> +class TMCCurrentHelper:
let's rename to `BaseTMCCurrentHelper`

2024-05-16 23:20 UTC, rogerlz commented on klippy/extras/tmc5160.py
> +        self.actual_current = self.req_run_current
yes it is.. did not notice I forgot it there

2024-05-22 15:56 UTC, bwnance submitted a review, later dismissed
i like this - i might take a swing at a reorg of this down the road but this is more than enough for now :)

2024-05-22 17:13 UTC, bwnance approved these changes

2024-05-22 17:14 UTC, merged