Updates docs\Bleeding_Edge.md example macro for pa tuning so that a f…
DangerKlippers/danger-klipper pull request #240
Opened 2024-05-13 20:59 UTC by Jakob-Eichberger

This pull request changes the example macro for the pa_test print found in docs\Bleeding_Edge.md to allow for very fine tuning of the pa value. It adds a pa_value and pa_range variable to the RUN_PA_TEST example macro where a pa value that should be tested around can be set. pa_range can be changed to increase/decreased the +/- range around the set pa_value. Setting pa_value to 0 deactivates this feature and prints the full pa test print starting from pa 0. 

Printed with pa_value set to zero to find the pa value that is somewhat correct:

![IMG20240513215319](https://github.com/DangerKlippers/danger-klipper/assets/53713395/469019ca-c3bf-4b79-9f48-28b77dad8297)

Printed with pa_value set to 0.025 and pa_range to 0.01. In this print, I missed the correct pa value in the picture. Currently, the default pa_range in the commit is 0.03 as that seems to be the sweet spot. 

![IMG20240513215517](https://github.com/DangerKlippers/danger-klipper/assets/53713395/39b4bd3d-0893-410b-b878-f3506854a503)

Issue can be found here: https://github.com/DangerKlippers/danger-klipper/issues/238

## Checklist

- [x] pr title makes sense
- [x] squashed to 1 commit
- [x] ci is happy and green

2024-05-15 21:46 UTC, YanceyA requested changes
Few minor changes to improve clarity of notes around actual variable names. Possibly a redundant If statement as noted. 

Thanks for the contribution.

2024-05-15 21:46 UTC, YanceyA commented on docs/Bleeding_Edge.md
> +variable_pa_value: 0             # Used for further tuning of pa value. If value is not 0 then the tested pa value will only be +/- (determined by the start_pa_test.range variable) around of the pava
change "pavalue" to pa_value to reflect actual variable name.
change "start_pa_test.range" to actual variable name so it's clear to the user.

2024-05-15 21:46 UTC, YanceyA commented on docs/Bleeding_Edge.md
> +variable_pa_range: 0.03          # Only use if pa_value is set to heigher then 0. Used to set the +/- area around pa_value that should be tested
then -> than

2024-05-15 21:46 UTC, YanceyA commented on docs/Bleeding_Edge.md
> +    {% if  vars.pa_value == 0 %}
is this IF statement required? Seems redundant with the line 298 if statement?  I'm only a novice coder so appologies if it is obvious why it is required.

2024-05-18 01:57 UTC, YanceyA approved these changes
No comments. Looks good to me.

2024-05-18 09:52 UTC, rogerlz approved these changes

2024-05-18 09:52 UTC, merged