Per Sensor temp_ignore_limits
DangerKlippers/danger-klipper pull request #261
Opened 2024-05-19 19:58 UTC by Zeanon

as discussed in Discord

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-05-19 20:02 UTC, Zeanon commented
I ran black on the files but it doesnt want to modify the spi_temperature but the ci doesnt like it, I dont really know where the issue is

2024-05-19 20:17 UTC, rogerlz commented on docs/Config_Reference.md
>  #   When set to true, this parameter ignores the min_value and max_value
missed updating the docs

2024-05-19 22:08 UTC, rogerlz commented
> I ran black on the files but it doesnt want to modify the spi_temperature but the ci doesnt like it, I dont really know where the issue is

sorted

2024-05-19 22:11 UTC, rogerlz commented
I think we should also support `temp_ignore_limits: all`. I also feel that `self.name in get_danger_options().temp_ignore_limits` could be DangerOptions() method.

2024-05-21 00:34 UTC, rogerlz commented
as we talked over discord, lets take the opportunity to make it per sensor.. the danger-option would stay as is to disable all at once.
feel free to close this pr and start a new one with the new implementation if you feel like
ty

2024-05-21 00:34 UTC, rogerlz requested changes
as we talked over discord, lets take the opportunity to make it per sensor.. the danger-option would stay as is to disable all at once.
feel free to close this pr and start a new one with the new implementation if you feel like
ty

2024-05-26 11:53 UTC, closed without merging