Check whether an adxl mcu is connected
DangerKlippers/danger-klipper pull request #270
Opened 2024-05-22 18:36 UTC by Zeanon

Add a check whether the mcu for an accelerometer is connected and error out early if not.

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-05-23 02:29 UTC, rogerlz commented
@bwnance

2024-05-23 02:50 UTC, bwnance requested changes
Also call check_connected in the run_test function for each chip

2024-05-23 02:50 UTC, bwnance commented on klippy/extras/adxl345.py
> +                "non_critical_mcu: ADXL [%s] is disconnected!" % self.name
f"ADXL: {self.name} could not connect because mcu: {self.mcu.name} is non_critical_disconnected!"

typing on phone so that syntax might be wrong, but let's include MCU name, and I'd rather not do brackets in messages, makes it harder to look for stuff.

2024-05-26 11:59 UTC, Zeanon commented
> Also call check_connected in the run_test function for each chip

Not nescessary
Every time an accelerometer gets instatiated, start_internal_client will be called, which calls the check_connected function
So either we iterate over all accelerometers twice (once for the check, second time for actual measurements) or if we dont, the result will be the same.

2024-05-26 18:20 UTC, bwnance approved these changes

2024-05-28 13:26 UTC, merged