sensorless: dwell once for all rails
DangerKlippers/danger-klipper pull request #298
Opened 2024-06-12 22:31 UTC by rogerlz

_Enter a good description of whats being changed and WHY

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-06-13 11:41 UTC, dalegaard requested changes

2024-06-13 11:41 UTC, dalegaard commented on klippy/extras/homing.py
> +        dwell_time = None
Use `dwell_time = 0.0`.

2024-06-13 11:41 UTC, dalegaard commented on klippy/extras/homing.py
>                          dwell_time = ch.current_change_dwell_time
`dwell_time = max(dwell_time, ch.current_change_dwell_time)`, remove the conditional

2024-06-13 11:41 UTC, dalegaard commented on klippy/extras/homing.py
>      def _set_current_post_homing(self, homing_axes):
Sidenote: maybe this and `_set_current_homing` should be folded in to one function with an extra parameter?

2024-06-13 11:41 UTC, dalegaard commented on klippy/extras/homing.py
> +        dwell_time = None
Same fix as above

2024-06-13 12:04 UTC, rogerlz commented on klippy/extras/homing.py
>      def _set_current_post_homing(self, homing_axes):
good idea

2024-06-14 07:10 UTC, dalegaard requested changes

2024-06-14 07:10 UTC, dalegaard commented on klippy/extras/homing.py
> +    def _set_current_homing(self, homing_axes, pre_homing=False):
Since this is an internal helper, I would remove the default for the last argument and force the callsite to set it.

Otherwise, this PR LGTM.

2024-06-15 16:36 UTC, dalegaard approved these changes

2024-06-15 18:04 UTC, merged