MPC: Increase accuracy
DangerKlippers/danger-klipper pull request #300
Opened 2024-06-13 15:22 UTC by darkjacky

This is a change to MPC to make the ambient heat loss actually make sense. See examples.

Command: MPC_CALIBRATE HEATER=extruder TARGET=230
Done on an Ender 3 V2 Neo with 40 Watt heating element, copper heat block.

Original:
0% fan average power: 21.81 W
50% fan average power: 20.74 W
100% fan average power: 21.01 W

0.1 temperature target:
0% fan average power: 20.86 W
50% fan average power: 20.68 W
100% fan average power: 20.50 W

heat soak and stabilization:
0% fan average power: 20.65 W
50% fan average power: 20.61 W
100% fan average power: 21.53 W

0.1 target, heat soak and stabilization:
0% fan average power: 20.23 W
50% fan average power: 21.01 W
100% fan average power: 21.97 W

The 0.1 degree target method was better in some ways but it did not have the desired effect. That is because the extruder isn't getting heat soaked.
Heat soaking and stabilization is way better, though it still is not perfect. (Perhaps it is not heat soaked enough? We might need to play around with the 0.05.)
Both methods seem to work best but it comes at a significant time cost. Given that you should basically run it and forget it I would say that is worth it.

This change has flaws. Certain hardware might not be able to stabilize properly and that will cause swings too high for the 0.1 degree target. Therefore the 0.1 degree should probably be configurable and maybe not the default.

An alternative would be to build another function to keep track of the PWM of the heater and wait for that to stabilize. It probably wouldn't matter much in terms of time though.

2024-06-16 09:17 UTC, dalegaard requested changes

2024-06-16 09:17 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
This range is too small. On many machines with noisy sensors, it's not possible to hold a target within 0.1 degrees. I like the idea of resetting the sampler until settling, but the way we do the check needs to be more robust.

One way we could do it is store the rate in the sample buffer and reset based on that?

2024-06-16 09:17 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            while samples[0][0] < eventtime - (min_time + 2.0):
This check isn't actually related to the minimum time, it's used to stop the buffer from holding more than 10 seconds of data. The intention was to avoid having the initial data affect the final result.

2024-06-16 09:17 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +        gcmd.respond_info("Waiting for heat soak")
Should probably just say "Waiting for temperature to stabilize" like the other logging addition, as heat soak has another meaning in 3D printing.

2024-06-16 10:13 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
Yes I agree.
I am not sure how you would like to store the rate though unless you mean doing
`samples.append((eventtime, rate))`
and then continue with something like a for loop? But that doesn't make sense in that case you might as well reset if the rate is too high. After all you calculate the rate anyway.

What is considered stable? If it goes above and below the target 10 times? So say we count up if below we set a flag if above and the flag is set we count. Once it reaches a certain amount we accept it? In that case the rate does not matter either does it? I would assume that is as stable as an extruder is going to get.

So that would make replace the function with something like this
```
below_target = True
above_target = 0
...
if below_target and temp > target:
    above_target++
    below_target = False
elif not below_target and temp < target:
    below_target = True
if above_target >= 10:
    return False
return True
```

This would be based on passing a threshold 10 times before it will be considered stable. This would fix the instability concern as it's purely based on counting and not based on any rate of change or time within the target range.

This would have be a different function though. As this would brick the await_ambient function.

Tell me if you think that would be better or if perhaps you want some hybrid of the old and the new.

2024-06-16 10:17 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            while samples[0][0] < eventtime - (min_time + 2.0):
I added the min_time as a variable to allow a longer wait time. So while your version might not be related so a minimum time my version is. You can set the min_time to 20 and it will keep 22 samples. As seen in the changes.

2024-06-16 10:18 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
That might work, potentially with some kind of limit on how fast it can transition between the two states? Would definitely be interested in seeing how that behaves in real life.

2024-06-16 10:21 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +        gcmd.respond_info("Waiting for heat soak")
In this case I wanted to distinguish between the heat soak (so the heatsink and sock will heat up slower for example) and a stable temperature so on line 565 I have stabilize again as at that point everything should be heat soaked. I understand your point but I don't like saying the same thing twice. Since one is in a loop the option is to just remove the line where it says "Waiting for heat soak".

2024-06-16 10:23 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
There is always the 1 second limit caused by the `self.printer.wait_while(process)` this only triggers once per second. So it should be fine.

2024-06-16 11:07 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
First test with 8 times before "heat soak" and 5 times between each test, it takes 3.5 minutes for the first time and about 1 minute 10 seconds between each test.

0% fan average power: 20.78 W
50% fan average power: 21.09 W
100% fan average power: 22.69 W

Now I will lower the amount of times required to cross the threshold value and see how it does.

2024-06-16 11:40 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
First test 5 times and in between 3 times. It takes about 2 minutes for the first time and still about 1 minute and 10 seconds in between each test.

0% fan average power: 20.47 W
50% fan average power: 21.00 W
100% fan average power: 21.58 W

It works. Those numbers are really close to the original proposal. Though there seems to be a large variable between this test and the last. Probably because it's only keeping track of the power usage over 20 seconds.

So I have added a function and reverted the wait_settle. Changed the wait_settle to wait_stable inside of transfer_test. We do self.wait_stable(5) for the first time after heating. and self.wait_stable(3) in between tests.

```
    def wait_stable(self, times = 5):
        below_target = True
        above_target = 0

        def process(eventtime):
            nonlocal below_target, above_target
            temp, target = self.heater.get_temp(eventtime)
            if below_target and temp > target:
                above_target += 1
                below_target = False
            elif not below_target and temp < target:
                below_target = True
            if above_target >= times:
                return False
            return True
        self.printer.wait_while(process)
```

What I don't like about this function is that it relies on a timer. It seems to be too slow to react to the temperature being stable. I will look for an alternative to the self.printer.wait_while function.

2024-06-16 11:46 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +        gcmd.respond_info("Waiting for heat soak")
Removing the line is fine by me.

2024-06-16 11:47 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            while samples[0][0] < eventtime - (min_time + 2.0):
I think the final window should be independent of the minimum time. If it should be configurable, it should be a separate parameter.

2024-06-16 11:49 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
We can change wait_while to take an interval parameter defaulting to 1.0, if the default sampling interval is too slow.

2024-06-16 11:53 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
Currently I changed my function to this to avoid having to change anything else:

```
    def wait_stable2(self, times = 5):
        below_target = True
        above_target = 0

        while True:
            eventtime = self.printer.reactor.monotonic()
            temp, target = self.heater.get_temp(eventtime)
            if below_target and temp > target:
                above_target += 1
                below_target = False
            elif not below_target and temp < target:
                below_target = True
            if above_target >= times:
                return
            self.printer.reactor.pause(eventtime + 0.1)
```
Strange enough it still seems to take about the same times. Though I am only testing at 100 degrees atm because I was not sure if this would work. Will test at my usual temperature in a little bit.

2024-06-16 12:02 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
If we do a custom wait, we should check the generation counter for interruption support. `wait_while` encapsulates that already so I recommend we use it and give it an interval instead.

2024-06-16 12:13 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
I already added those while waiting for the extruder to cool down.

```
    def wait_stable2(self, times = 5):
        below_target = True
        above_target = 0
        gcode = self.printer.lookup_object("gcode")
        counter = gcode.get_interrupt_counter()
        eventtime = self.printer.reactor.monotonic()

        while True:
            if self.printer.is_shutdown() or counter != gcode.get_interrupt_counter():
                return;
            temp, target = self.heater.get_temp(eventtime)
            if below_target and temp > target:
                above_target += 1
                below_target = False
            elif not below_target and temp < target:
                below_target = True
            if above_target >= times:
                return
            eventtime = self.printer.reactor.pause(eventtime + 0.1)
```

I however failed to read properly and didn't see that I forgot the .printer at is_shutdown() so now I have to wait for cool down again. I will be back in 40 minutes.

Obviously the alternative would be to implement a wait_while function into the MPC base directly. That depends on your preference. I would simply copy paste the existing function wait_while into the the MPC file and then add the required variable.

```
    def wait_while(self, condition_cb, error_on_cancel=True):
        """
        receives a callback
        waits until callback returns False
            (or is interrupted, or printer shuts down)
        """
        gcode = self.lookup_object("gcode")
        counter = gcode.get_interrupt_counter()
        eventtime = self.reactor.monotonic()
        while condition_cb(eventtime):
            if self.is_shutdown() or counter != gcode.get_interrupt_counter():
                if error_on_cancel:
                    raise WaitInterruption("Command interrupted")
                else:
                    return
            eventtime = self.reactor.pause(eventtime + 1.0)
```

2024-06-16 12:35 UTC, darkjacky commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
0% fan average power: 20.51 W
50% fan average power: 20.94 W
100% fan average power: 22.19 W

Those results are within the expected margin. So the code works. Would you like me to make a local version of the wait_while?

2024-06-16 13:26 UTC, dalegaard commented on klippy/extras/control_mpc.py
> +            if target > 1 and abs(target - temp) > 0.1:
I think giving the general wait_while an interval argument is better because I can see there being other cases where this will be needed. The static interval stems from the code that was replaced when the wait_while helper was added. A default interval parameter of 1.0 seems like the cleanest solution to me.

We can safely change this because there are very few wait_while call sites today, and with a default parameter there should be no change in functionality for existing callers.

2024-06-21 18:10 UTC, dalegaard approved these changes

2024-06-21 18:49 UTC, merged