bugfix: sensorless return to run current
DangerKlippers/danger-klipper pull request #304
Opened 2024-06-16 11:47 UTC by rogerlz

I introduced a bug in https://github.com/DangerKlippers/danger-klipper/pull/298. 
`_set_current_homing` and `_set_current_post_homing` were consolidated into a single method, and I missed the difference between `ch.needs_home_current_change` and `ch.needs_run_current_change`.

A new method, `ch.needs_any_current_change`, now validates if any current needs changing.  

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-06-16 11:58 UTC, dalegaard commented on klippy/extras/homing.py
> +                if ch is not None and ch.needs_running_current_change():
This feels icky to me somehow. Best I can tell, all the functions for changing homing current are called _only_ from here?

Could we instead introduce `{get,set}_actual_current` and `get_{homing,normal}_current`? Logic then becomes:
```python
if pre_homing:
  target_current = ch.get_homing_current()
else:
  target_current = ch.get_normal_current()
if target_current != ch.get_actual_current():
  dwell_time = max(dwell_time, ch.current_change_dwell_time)
  ch.set_actual_current(target_current)
```

2024-06-16 23:11 UTC, dalegaard requested changes

2024-06-16 23:11 UTC, dalegaard commented on klippy/extras/tmc.py
> +    def set_current_for_homing(self, print_time) -> float:
This and `set_current_for_normal` are almost identical, seems ripe for merging logic.

2024-06-16 23:11 UTC, dalegaard commented on klippy/extras/homing.py
> +                        dwell_time = ch.set_current_for_homing(print_time)
Needs `max(dwell_time, ...)`?

2024-06-16 23:47 UTC, rogerlz commented on klippy/extras/homing.py
> +                        dwell_time = ch.set_current_for_homing(print_time)
duh, forgot that

2024-06-16 23:58 UTC, rogerlz commented on klippy/extras/tmc.py
> +    def set_current_for_homing(self, print_time) -> float:
yeah! good finding. I can also call `self.set_current()` only once if we feel like it

2024-06-17 06:07 UTC, dalegaard approved these changes

2024-06-17 11:10 UTC, merged