Update MPC.md
DangerKlippers/danger-klipper pull request #309
Opened 2024-06-19 08:17 UTC by rschaeuble

Fix the description of MPC_CALIBRATE's TARGET parameter, so that it reflects what the code really is doing.

Note: the docs previously contradicted themselves (90C vs. 100C). I picked 100C, but if that was the wrong choice, it should be corrected in both places.

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-06-19 21:46 UTC, YanceyA requested changes
Hey Rolf, thanks for the feedback. No problems with the content. I have a suggestion to make it more clear:

Current: "For the bed it has to be set to a suitable value (suggested: 100C)."

Suggested change: "For the bed, 100C is the suggested temperature target."  

Also, while we are making this change do you mind fixing a typo in the following sentence.  calibration -> calibrating:
 "..independent so calibration the extruder.."

2024-06-20 05:04 UTC, rschaeuble commented
@YanceyA Those are good suggestions; I've applied them (and fixed some punctuation).

2024-06-20 21:46 UTC, YanceyA approved these changes
Looks good, no notes. Thanks Rolf!

2024-06-20 21:48 UTC, rogerlz approved these changes

2024-06-20 21:48 UTC, merged