feat/tmc - warning for sense_resistor
DangerKlippers/danger-klipper pull request #332
Opened 2024-07-04 13:08 UTC by rogerlz

https://github.com/DangerKlippers/danger-klipper/issues/325

We want to make sense_resistor mandatory in the future, but let's warn it first and avoid breaking existing configs.

![image](https://github.com/DangerKlippers/danger-klipper/assets/1423595/3243f7f0-9302-4d96-a61a-d2147999ecac)

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-07-04 22:52 UTC, calithameridi commented
I think this is a good compromise. Maybe "specify the parameter to resolve this warning" would be better phrasing

2024-07-04 22:52 UTC, calithameridi commented
We would also want the same on [temperature_sensor]'s pullup_resistor

2024-07-05 00:22 UTC, rogerlz commented
> We would also want the same on [temperature_sensor]'s pullup_resistor

would you mind sharing your thoughts? temperature sensors already include the sensor type, significantly reducing the likelihood of incorrect configurations. unlike the TMC, an incorrect pull-up value is very noticeable

2024-07-05 07:01 UTC, calithameridi commented
It doesn't cost anything to at least implement that as a warning at least, and it's useful information to the user. Sure min_temp and max_temp should catch most configurations but I bet there's at least a few byzantine edge case that'll cause issues with nonzero probability.

2024-07-08 17:43 UTC, dalegaard commented
Hi,

I agree with @calithameridi on this point. Any hardware constant shouldn't be assumed and always specified by the user.

Best regards,
Lasse

2024-07-08 17:47 UTC, dalegaard requested changes
I think the 2660 should also get this warning?

2024-07-08 20:36 UTC, rogerlz commented
> I think the 2660 should also get this warning?

sense_resistor for 2660 is already mandatory.

2024-07-08 20:38 UTC, rogerlz commented
I will do `pullup_resistor` in another PR

2024-07-09 20:09 UTC, dalegaard commented
> > I think the 2660 should also get this warning?
> 
> sense_resistor for 2660 is already mandatory.

I super, I missed that. LGTM then!

2024-07-09 20:09 UTC, dalegaard approved these changes

2024-07-18 09:33 UTC, merged