Autodetect Beacon for homing z
DangerKlippers/danger-klipper pull request #383
Opened 2024-10-10 15:21 UTC by Zeanon

Automatically detect beacon for z-homing (like autodetecting sensorless homing) and set the appropriate settings by default to make sure users who dont read the doc fully dont put in wrong settings and to clean up the config/make it easier for everyone else

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-10-18 09:07 UTC, rogerlz commented on README.md
> +- [Homing: autodetect if beacon is used for z-homing and set the retract_dist to 0](https://github.com/DangerKlippers/danger-klipper/pull/383)
`s/H/h`

2024-10-18 09:07 UTC, rogerlz commented
looks good to me.. would you please add a comment to the config reference about this change too?

2024-10-29 00:43 UTC, rogerlz requested changes

2024-10-29 00:43 UTC, rogerlz commented on docs/Config_Reference.md
> +#homing_retract_dist: 5.0 by default, if you are using beacon (the beacon module is installed and probe:z_virtual_endstop is used)
It seems incomplete and it is in the wrong location. Please check: https://github.com/DangerKlippers/danger-klipper/blob/master/docs/Config_Reference.md#L270

2024-10-29 00:43 UTC, rogerlz commented on README.md
> +- [Homing: autodetect if beacon is used for z-homing and set the retract_dist to 0](https://github.com/DangerKlippers/danger-klipper/pull/383)
please rename `Homing` to `homing`.

2024-10-29 09:49 UTC, Zeanon commented
Closing it for now as I have to figure out a more reliable way of doing it with dalegaard

2024-10-29 09:49 UTC, closed without merging